default:
	echo "\setbeamercolor{normal text}{fg=black,bg=white}" >color.tex
	echo "\definecolor{h1}{RGB}{255,0,0} %red" >>color.tex
	echo "\definecolor{h2}{RGB}{0,255,0} %green" >>color.tex
	pdflatex presentation.tex

theme1:
	echo "\setbeamercolor{normal text}{fg=green,bg=black}" >color.tex
	echo "\setbeamercolor{structure}{fg=brown}" >>color.tex
	echo "\definecolor{h1}{RGB}{255,0,0} %red" >>color.tex
	echo "\definecolor{h2}{RGB}{255,255,0} %yellow" >>color.tex
	pdflatex presentation.tex

theme2:
	echo "\setbeamercolor{normal text}{fg=black,bg=Apricot}" >color.tex
	echo "\definecolor{h1}{RGB}{220,0,0} %red" >>color.tex
	echo "\definecolor{h2}{RGB}{0,0,255} %blue" >>color.tex
	pdflatex presentation.tex
